### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by nicholasikiroma**
Forget password pages

### CODE REVIEW

**Comment by Pythonian** [comment]
From your end, can you like your PR to your issue task #2?

**Comment by nicholasikiroma** [comment]
Sorry, I don't fully understand what you mean.

**Comment by nicholasikiroma** [comment]
Do you want me to merge from my end?

**Comment by Pythonian** [comment]
@nicholasikiroma Alright, don't worry, I'll manage it from here. I'll update you on what should be done before your next PR. Sorry about the inconvenience.

**Comment by nicholasikiroma** [comment]
Okay bro.

**Pull request merged**
